### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by arsenicks** [RadarRelay/sdk-bot-example#8]
I did the npm install and I can't start after that. Does the bot still functioning with RadarRelayV2 or I just missed something ?

```
$ npm install
npm WARN bitcore-mnemonic@1.7.0 requires a peer of bitcore-lib@^0.16.0 but none was installed.
npm WARN radar-relay-bot@0.0.1 No repository field.
```

That's the output when I try to start it, Ubuntu 18.04, node v8.10.0, npm  v3.5.2.

```
$ npm start

> radar-relay-bot@0.0.1 start /home/XXXXX/git-repository/DEXBot01/sdk-bot-example
> npm run build && node dist/index.js


> radar-relay-bot@0.0.1 build /home/XXXXX/git-repository/DEXBot01/sdk-bot-example
> tsc

/home/XXXXX/git-repository/DEXBot01/sdk-bot-example/node_modules/@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:120
      var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(_) {
                                                 ^

ReferenceError: regeneratorRuntime is not defined
    at /home/XXXXX/git-repository/DEXBot01/sdk-bot-example/node_modules/@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:120:50
    at /home/XXXXX/git-repository/DEXBot01/sdk-bot-example/node_modules/@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:142:6
    at Object.<anonymous> (/home/XXXXX/git-repository/DEXBot01/sdk-bot-example/node_modules/@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:224:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

npm ERR! Linux 4.15.0-43-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! radar-relay-bot@0.0.1 start: `npm run build && node dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the radar-relay-bot@0.0.1 start script 'npm run build && node dist/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the radar-relay-bot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && node dist/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs radar-relay-bot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls radar-relay-bot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/XXXXX/git-repository/DEXBot01/sdk-bot-example/npm-debug.log
```

That's the debug file: [npm-debug.log](https://github.com/RadarRelay/sdk-bot-example/files/2739183/npm-debug.log)

**Comment by arsenicks** [comment]
Hi, thanks for the reply. I didn't modified anything. To be honest I'm not used to this, I was following the [Bot Tutorial](https://developers.radarrelay.com/bot-tutorial/#install-nodejs) and trying to lear and see if I would be able to build something from that.

So I followed the documentation step by step on a Ubuntu 18.04.

```
$ cat tsconfig.json
{
    "compilerOptions": {
      "module": "commonjs",
      "target": "es6",
      "outDir": "dist",
      "declaration": true
    },
    "include": [
      "src/**/*"
    ]
  }

$ npm install
npm WARN bitcore-mnemonic@1.7.0 requires a peer of bitcore-lib@^0.16.0 but none was installed.
npm WARN radar-relay-bot@0.0.1 No repository field.


$ npm start

> radar-relay-bot@0.0.1 start ~/git-repository/DEXBot01/sdk-bot-example
> npm run build && node dist/index.js


> radar-relay-bot@0.0.1 build ~/git-repository/DEXBot01/sdk-bot-example
> tsc

~/git-repository/DEXBot01/sdk-bot-example/node_modules/@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:120
      var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(_) {
                                                 ^

ReferenceError: regeneratorRuntime is not defined
    at ~/git-repository/DEXBot01/sdk-bot-example/node_modules/@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:120:50
    at ~/git-repository/DEXBot01/sdk-bot-example/node_modules/@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:142:6
    at Object.<anonymous> (~/git-repository/DEXBot01/sdk-bot-example/node_modules/@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:224:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

npm ERR! Linux 4.15.0-44-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! radar-relay-bot@0.0.1 start: `npm run build && node dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the radar-relay-bot@0.0.1 start script 'npm run build && node dist/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the radar-relay-bot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && node dist/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs radar-relay-bot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls radar-relay-bot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/git-repository/DEXBot01/sdk-bot-example/npm-debug.log


$ dpkg -l |grep npm
ii  node-npmlog                                0.0.4-1                                      all          Logger with custom levels and colored output for Node.js
ii  node-read-package-json                     1.2.4-1                                      all          Read package.json for npm module for Node.js
ii  node-validate-npm-package-license          3.0.1-1                                      all          Tells if a string is a valid npm package license string
ii  npm                                        3.5.2-0ubuntu4                               all          package manager for Node.js

$ dpkg -l |grep nodejs
ii  nodejs                                     8.10.0~dfsg-2ubuntu0.4                       amd64        evented I/O for V8 javascript
ii  nodejs-dev                                 8.10.0~dfsg-2ubuntu0.4                       amd64        evented I/O for V8 javascript (development files)
ii  nodejs-doc                                 8.10.0~dfsg-2ubuntu0.4                       all          API documentation for Node.js, the javascript platform

```

**Comment by czarly** [comment]
I have the exact same problem as the initial reporter. But I'm running MacOSX Mojave and Node 11.13.0.

I tried the suggested fix. "lib":["2015"] was not working as it should be "lib":["es2015"] - after replacing that i get a different error:

> radar-relay-bot@0.0.1 build /Users/sebastian/nodeenv/sdk-bot-example
> tsc

node_modules/@0xproject/utils/lib/src/fetch_async.d.ts:3:63 - error TS2304: Cannot find name 'RequestInit'.

3 export declare const fetchAsync: (endpoint: string, options?: RequestInit, timeoutMs?: number) => Promise<Response>;
                                                                ~~~~~~~~~~~


node_modules/@0xproject/utils/lib/src/fetch_async.d.ts:3:107 - error TS2304: Cannot find name 'Response'.

3 export declare const fetchAsync: (endpoint: string, options?: RequestInit, timeoutMs?: number) => Promise<Response>;
                                                                                                            ~~~~~~~~

**Comment by dchambers** [comment]
I hit a number of issues when attempting to install (including the one described here) so I've created #11 to address.
